channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=24.3.1
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - pathlib==1.0.1
  - psutil==6.1.1
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
